In [1]:
import pandas as pd

p= 'https://assets.datacamp.com/production/repositories/655/datasets/1304e66b1f9799e1a5eac046ef75cf57bb1dd630/company-stock-movements-2010-2015-incl.csv'

df = pd.read_csv(p)

In [2]:
df.head()

,Unnamed: 0,2010-01-04,2010-01-05,2010-01-06,2010-01-07,2010-01-08,2010-01-11,2010-01-12,2010-01-13,2010-01-14,...,2013-10-16,2013-10-17,2013-10-18,2013-10-21,2013-10-22,2013-10-23,2013-10-24,2013-10-25,2013-10-28,2013-10-29
0,Apple,0.580000,-0.220005,-3.409998,-1.170000,1.680011,-2.689994,-1.469994,2.779997,-0.680003,...,0.320008,4.519997,2.899987,9.590019,-6.540016,5.959976,6.910011,-5.359962,0.840019,-19.589981
1,AIG,-0.640002,-0.650000,-0.210001,-0.420000,0.710001,-0.200001,-1.130001,0.069999,-0.119999,...,0.919998,0.709999,0.119999,-0.480000,0.010002,-0.279998,-0.190003,-0.040001,-0.400002,0.660000
2,Amazon,-2.350006,1.260009,-2.350006,-2.009995,2.960006,-2.309997,-1.640007,1.209999,-1.790001,...,2.109985,3.699982,9.570008,-3.450013,4.820008,-4.079986,2.579986,4.790009,-1.760009,3.740021
3,American express,0.109997,0.000000,0.260002,0.720002,0.190003,-0.270001,0.750000,0.300004,0.639999,...,0.680001,2.290001,0.409996,-0.069999,0.100006,0.069999,0.130005,1.849999,0.040001,0.540001
4,Boeing,0.459999,1.770000,1.549999,2.690003,0.059997,-1.080002,0.360000,0.549999,0.530002,...,1.559997,2.480003,0.019997,-1.220001,0.480003,3.020004,-0.029999,1.940002,1.130005,0.309998

In [3]:
movements = df.drop('Unnamed: 0', axis=1).values

In [6]:
# Import Normalizer
from sklearn.preprocessing import Normalizer
from sklearn.pipeline import make_pipeline
from sklearn.cluster import KMeans

# Create a normalizer: normalizer
normalizer = Normalizer()

# Create a KMeans model with 10 clusters: kmeans
kmeans = KMeans(10)

# Make a pipeline chaining normalizer and kmeans: pipeline
pipeline = make_pipeline(normalizer, kmeans)

# Fit pipeline to the daily price movements
pipeline.fit(movements)

Pipeline(memory=None,
         steps=[('normalizer', Normalizer(copy=True, norm='l2')),
                ('kmeans',
                 KMeans(algorithm='auto', copy_x=True, init='k-means++',
                        max_iter=300, n_clusters=10, n_init=10, n_jobs=None,
                        precompute_distances='auto', random_state=None,
                        tol=0.0001, verbose=0))],
         verbose=False)

In [7]:
# Import pandas
import pandas as pd

# Predict the cluster labels: labels
labels = pipeline.predict(movements)

# Create a DataFrame aligning labels and companies: df
pre = pd.DataFrame({'labels': labels, 'companies': df['Unnamed: 0']})

# Display df sorted by cluster label
print(pre.sort_values('labels'))

    labels                           companies
55       0                         Wells Fargo
26       0                      JPMorgan Chase
5        0                     Bank of America
18       0                       Goldman Sachs
25       1                   Johnson & Johnson
54       1                            Walgreen
27       1                      Kimberly-Clark
40       1                      Procter Gamble
39       1                              Pfizer
56       1                            Wal-Mart
32       2                                  3M
33       2                           Microsoft
47       2                            Symantec
30       2                          MasterCard
58       2                               Xerox
35       2                            Navistar
44       2                        Schlumberger
43       2                                 SAP
23       2                                 IBM
59       2                               Yahoo
20       2                          Home Depot
10       2                      ConocoPhillips
1        2                                 AIG
2        2                              Amazon
16       2                   General Electrics
53       2                       Valero Energy
13       2                   DuPont de Nemours
3        2                    American express
12       2                             Chevron
11       2                               Cisco
57       2                               Exxon
8        2                         Caterpillar
37       3                            Novartis
46       3                      Sanofi-Aventis
42       3                   Royal Dutch Shell
19       3                     GlaxoSmithKline
49       3                               Total
52       3                            Unilever
6        3            British American Tobacco
24       4                               Intel
50       4  Taiwan Semiconductor Manufacturing
51       4                   Texas instruments
0        5                               Apple
17       5                     Google/Alphabet
38       6                               Pepsi
9        6                   Colgate-Palmolive
31       6                           McDonalds
28       6                           Coca Cola
41       6                       Philip Morris
14       7                                Dell
22       7                                  HP
7        8                               Canon
15       8                                Ford
21       8                               Honda
34       8                          Mitsubishi
45       8                                Sony
48       8                              Toyota
36       9                    Northrop Grumman
4        9                              Boeing
29       9                     Lookheed Martin